<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PedidosYosel.Application\PedidosYosel.Application.csproj" />
    <ProjectReference Include="..\PedidosYosel.Domain\PedidosYosel.Domain.csproj" />
  </ItemGroup>

</Project>
